# Generated by Django 5.1.2 on 2024-10-22 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_de_indicadores', '0002_criar_setor_de_seguranca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo_de_tempo_limite', models.CharField(max_length=10)),
                ('tempo_limite', models.PositiveIntegerField()),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_de_indicadores.setor')),
            ],
        ),
    ]
