# Generated by Django 5.1.2 on 2024-10-22 03:50

from django.db import migrations

def criar_indicadores_seguranca(apps, schema_editor):
    Setor = apps.get_model('gestao_de_indicadores', 'Setor')
    Indicador = apps.get_model('gestao_de_indicadores', 'Indicador')

    setor = Setor.objects.get(nome='Segurança')

    Indicador.objects.create(nome='Auditorias', tipo_de_tempo_limite='horas', tempo_limite=7, setor=setor)
    Indicador.objects.create(nome='Atestados', tipo_de_tempo_limite='dias', tempo_limite=3, setor=setor)
    Indicador.objects.create(nome='Step Auditoria', tipo_de_tempo_limite='dias', tempo_limite=6, setor=setor)
    Indicador.objects.create(nome='PRE', tipo_de_tempo_limite='dias', tempo_limite=6, setor=setor)
    Indicador.objects.create(nome='Laudos e Programas', tipo_de_tempo_limite='dias', tempo_limite=6, setor=setor)

class Migration(migrations.Migration):

    dependencies = [
        ('gestao_de_indicadores', '0003_indicador'),
    ]

    operations = [
        migrations.RunPython(criar_indicadores_seguranca),
    ]
