# Generated by Django 5.1.2 on 2024-10-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_de_indicadores', '0004_criar_indicadores_seguranca'),
        ('gestao_de_indicadores', '0005_indicador_created_at_indicador_updated_at_and_more'),
    ]

    operations = [
    ]
