# Generated by Django 5.1.2 on 2024-10-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_de_indicadores', '0006_merge_20241022_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
