# Generated by Django 5.1.2 on 2024-11-02 20:26

from django.db import migrations

def criar_indicador_painel_kpi(apps, schema_editor):
    Setor = apps.get_model('gestao_de_indicadores', 'Setor')
    Indicador = apps.get_model('gestao_de_indicadores', 'Indicador')

    setor = Setor.objects.get(nome='Segurança')

    Indicador.objects.create(nome='Painel KPI', tipo_de_tempo_limite='', tempo_limite=0, setor=setor)


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_de_indicadores', '0003_indicador'),
    ]

    operations = [
        migrations.RunPython(criar_indicador_painel_kpi),
    ]
