# Generated by Django 5.1.2 on 2024-11-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_de_indicadores', '0009_alter_servico_indicador'),
        ('gestao_de_indicadores', '0010_criar_indicador_painel_kpi'),
    ]

    operations = [
    ]
