# Generated by Django 5.1.2 on 2024-11-02 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_de_indicadores', '0011_merge_20241102_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='indicador_geral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicador',
            name='indicador_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subindicadores', to='gestao_de_indicadores.indicador'),
        ),
    ]
