# Generated by Django 5.1.2 on 2024-11-02 21:04

from django.db import migrations

def vincular_indicador_pai(apps, schema_editor):
    Indicador = apps.get_model('gestao_de_indicadores', 'Indicador')

    indicador_geral = Indicador.objects.get(nome='Painel KPI')
    indicador_geral.indicador_geral = True
    indicador_geral.save()

    indicadores = ["Auditorias", "Atestados", "Step Auditoria", "PRE", "Laudos e Programas"]
    for indicador in indicadores:
        indicador = Indicador.objects.get(nome=indicador)
        indicador.indicador_pai = indicador_geral
        indicador.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gestao_de_indicadores', '0012_indicador_indicador_geral_indicador_indicador_pai'),
    ]

    operations = [
        migrations.RunPython(vincular_indicador_pai),
    ]
