# Generated by Django 5.1.3 on 2024-11-12 01:55

from django.db import migrations

def adicionar_ordenacao(apps, schema_editor):
    Indicador = apps.get_model('gestao_de_indicadores', 'Indicador')

    indicadores_ordenacao = {
        "Auditorias": 1,
        "Atestados": 2,
        "Step Auditoria": 3,
        "PRE": 4,
        "Laudos e Programas": 5,
        "Painel KPI": 6
    }

    for indicador_nome, ordenacao in indicadores_ordenacao.items():
        indicador = Indicador.objects.get(nome=indicador_nome)
        indicador.ordenacao = ordenacao
        indicador.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gestao_de_indicadores', '0014_indicador_ordenacao'),
    ]

    operations = [
        migrations.RunPython(adicionar_ordenacao),
    ]
